import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import './styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Script src="/bootstrap-italia/dist/js/bootstrap-italia.bundle.min.js" strategy="beforeInteractive" />
      </body>
    </html>
  )
}
